package com.tracker.entity;

import org.junit.jupiter.api.Test;

import java.time.LocalDate;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for {@link Job}.
 */
class JobTest {

    /** No-arg constructor should default status to "Applied". */
    @Test
    void defaultConstructor_setsStatusToApplied() {
        Job job = new Job();
        assertEquals("Applied", job.getStatus());
    }

    /** No-arg constructor should default dateApplied to today. */
    @Test
    void defaultConstructor_setsDateAppliedToToday() {
        Job job = new Job();
        assertEquals(LocalDate.now(), job.getDateApplied());
    }

    /** No-arg constructor should initialise statusHistory as an empty list, not null. */
    @Test
    void defaultConstructor_statusHistoryIsEmptyList() {
        Job job = new Job();
        assertNotNull(job.getStatusHistory());
        assertTrue(job.getStatusHistory().isEmpty());
    }

    /** Full constructor should populate every field correctly. */
    @Test
    void fullConstructor_setsAllFields() {
        User user = new User("sub-001");
        LocalDate date = LocalDate.of(2024, 6, 1);

        Job job = new Job(user, "Acme Corp", "Software Engineer",
                "Remote", "$120k-$140k", "Interviewing",
                "https://jobs.acme.com/123", "Build cool stuff.", date);

        assertAll(
                () -> assertEquals(user, job.getUser()),
                () -> assertEquals("Acme Corp", job.getCompanyName()),
                () -> assertEquals("Software Engineer", job.getJobTitle()),
                () -> assertEquals("Remote", job.getLocation()),
                () -> assertEquals("$120k-$140k", job.getSalaryRange()),
                () -> assertEquals("Interviewing", job.getStatus()),
                () -> assertEquals("https://jobs.acme.com/123", job.getJobUrl()),
                () -> assertEquals("Build cool stuff.", job.getDescription()),
                () -> assertEquals(date, job.getDateApplied())
        );
    }

    /** Setters generated by Lombok should update the field value. */
    @Test
    void setters_updateFields() {
        Job job = new Job();
        job.setCompanyName("NewCo");
        job.setStatus("Offer");

        assertEquals("NewCo", job.getCompanyName());
        assertEquals("Offer", job.getStatus());
    }
}
