appenders = console

appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%-5level] %d{yyyy-MM-dd hh:mm:ss a} [%t] %c{1} - %msg%n

loggers = app, hibernate

logger.app.name = com.tracker
logger.app.level = info
logger.app.appenderRefs = stdout
logger.app.appenderRef.stdout.ref = STDOUT
logger.app.additivity = false

logger.hibernate.name = org.hibernate
logger.hibernate.level = warn
logger.hibernate.appenderRefs = stdout
logger.hibernate.appenderRef.stdout.ref = STDOUT
logger.hibernate.additivity = false

rootLogger.level = error
rootLogger.appenderRefs = stdout
rootLogger.appenderRef.stdout.ref = STDOUT