appenders = console, file

appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%-5level] %d{yyyy-MM-dd hh:mm:ss a} [%t] %c{1} - %msg%n

appender.file.type = RollingFile
appender.file.name = FILE
appender.file.fileName = ${sys:catalina.home}/logs/job-tracker.log
appender.file.filePattern = ${sys:catalina.home}/logs/job-tracker-%d{yyyy-MM-dd}.log.gz
appender.file.layout.type = PatternLayout
appender.file.layout.pattern = [%-5level] %d{yyyy-MM-dd hh:mm:ss a} [%t] %c{1} - %msg%n
appender.file.policies.type = Policies
appender.file.policies.time.type = TimeBasedTriggeringPolicy
appender.file.policies.time.interval = 1
appender.file.policies.time.modulate = true

loggers = app, hibernate

logger.app.name = com.tracker
logger.app.level = info
logger.app.appenderRefs = stdout, file
logger.app.appenderRef.stdout.ref = STDOUT
logger.app.appenderRef.file.ref = FILE
logger.app.additivity = false

logger.hibernate.name = org.hibernate
logger.hibernate.level = warn
logger.hibernate.appenderRefs = stdout, file
logger.hibernate.appenderRef.stdout.ref = STDOUT
logger.hibernate.appenderRef.file.ref = FILE
logger.hibernate.additivity = false

rootLogger.level = error
rootLogger.appenderRefs = stdout, file
rootLogger.appenderRef.stdout.ref = STDOUT
rootLogger.appenderRef.file.ref = FILE
